### ISSUE TITLE
Status check

### ISSUE THREAD

**Issue by altendky** [tox-dev/tox-via-docker#1]
A quick look doesn't show any real implementation here.  Am I missing it?  If I am not, is there any more implementation of this elsewhere?

Cheers,
-kyle

**Comment by gaborbernat** [comment]
I've been focusing until now on the virtualenv rewrite. That's very close now, probably will happen early next week. I'm expecting some follow-up work on that, so most likely I'll be returning to the tox rewrite in early March... So probably first beta possible around May is my best guest for this.

**Comment by altendky** [comment]
Thanks for the quick reply and estimated schedule.  I promise I won't hold you to it.  `:]`

**Comment by imomaliev** [comment]
Hi, I wanted to work on something similar. I see that this already in the works. I would be happy to help with this project.

**Comment by gaborbernat** [comment]
So virtualenv release went through a few bumps (more details will follow at https://ep2020.europython.eu/talks/D2SG8Vb-lessons-from-the-trenches-rewriting-and-re-releasing-virtualenv/), so this has been pushed back to September for tox 4... and this library more like in November is my best realistic guess.
